[package]
name = "kakasi"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "crates/core",
]

[dependencies]
anyhow = "1.0.57"
clap = "3.2.5"

[[bin]]
name = "kakasi"
path = "src/main.rs"

